---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Launch the EC2 Instance
      ec2:
        region: ap-northeast-1
        group: default
        keypair: ansible
        instance_type: t2.micro
        image: ami-0f310fced6141e627
        vpc_subnet_id: subnet-720acd3a
        assign_public_ip: yes
        wait: yes
        #wait_timeout: 600
        instance_tags:
           Name: "EC2-ansible"
      register: ec2

    - name: Adding Public IP into Inventory
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: ec2_group
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_ip }}"
        port: 22
        state: started
      with_items: "{{ ec2.instances }}"

- hosts: ec2_group
  tasks:
     - name: Installing Docker on EC2 instance
       command: yum install docker -y

